#ifndef LIBCHECKSUM_GLOBAL_H
#define LIBCHECKSUM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBCHECKSUM_LIBRARY)
#  define LIBCHECKSUMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBCHECKSUMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCHECKSUM_GLOBAL_H
