#ifndef CONFIGURATIONMANAGER_GLOBAL_H
#define CONFIGURATIONMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONFIGURATIONMANAGER_LIBRARY)
#  define CONFIGURATIONMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONFIGURATIONMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONFIGURATIONMANAGER_GLOBAL_H
