#ifndef CHUNKHANDLER_GLOBAL_H
#define CHUNKHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHUNKHANDLER_LIBRARY)
#  define CHUNKHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHUNKHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHUNKHANDLER_GLOBAL_H
