#ifndef FILEHANDLER_GLOBAL_H
#define FILEHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEHANDLER_LIBRARY)
#  define FILEHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEHANDLER_GLOBAL_H
