#ifndef DELTAHANDLER_GLOBAL_H
#define DELTAHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DELTAHANDLER_LIBRARY)
#  define DELTAHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DELTAHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DELTAHANDLER_GLOBAL_H
